Clean pod cache
fwartner/homebrew-mac-cleanup pull request #65
Opened 2021-03-25 07:54 UTC by luutruong

2021-03-25 08:25 UTC, fwartner commented
Hey thank you for this awesome PR! Would you like to add your additions to the readme as well? If this is done, I am happy to merge!

2021-03-25 09:25 UTC, luutruong commented
Updated now ;)

2021-03-25 10:50 UTC, fwartner requested changes

2021-03-25 10:50 UTC, fwartner commented on README.md
> +* Cleanup Pod (CocoaPods) cache
Duplicate

2021-03-26 15:39 UTC, fwartner approved these changes

2021-03-26 15:39 UTC, merged